import type { ArticleMeta } from '../../types'

const article: ArticleMeta = {
  slug: '2026-04-17-deep-strapi-npm-supply-chain-red-team',
  date: '2026-04-17',
  author: 'AEGIDA Research Team',
  category: 'deep-analysis',
  locales: {
    it: {
      title: '36 Pacchetti npm Malevoli Travestiti da Plugin Strapi: Ricostruzione Red Team dell\'Attacco Supply Chain a Guardarian',
      excerpt: 'Trentasei pacchetti npm pubblicati in tredici ore da quattro account fake. Otto varianti di malware in evoluzione rapida. Un solo bersaglio: la piattaforma crypto Guardarian. Questa non è un\'analisi di minaccia tradizionale. È la ricostruzione dell\'operazione dal punto di vista dell\'attaccante, fase per fase, dal banco di lavoro di chi progetta attacchi supply chain. Con indicazioni difensive a ogni svolta.',
      body: [
        { type: 'heading', level: 2, text: 'Premessa: Perché Leggere dal Punto di Vista dell\'Attaccante' },
        { type: 'paragraph', text: 'Questo articolo è scritto in una forma diversa dal solito. Invece di descrivere un incidente dall\'esterno, ricostruiamo la logica operativa dall\'interno: ogni fase è narrata dal punto di vista di chi ha progettato l\'attacco. Non è glorificazione. È reverse engineering del pensiero avversario, lo stesso metodo che i red team professionisti usano per anticipare le mosse di chi attacca. Se capite come ragiona l\'attaccante, capite dove si rompe la catena difensiva. Ogni sezione "attaccante" è seguita da un box difensivo che riporta la prospettiva al lato blu.' },
        { type: 'paragraph', text: 'Il caso è reale: tra il 14 e il 15 aprile 2026, 36 pacchetti npm malevoli mascherati da plugin per Strapi CMS sono stati pubblicati sul registry npm. Il bersaglio finale era Guardarian, piattaforma di scambio criptovalute. L\'operazione ha attraversato otto varianti di malware in tredici ore, partendo da credential harvesting generico e arrivando a esecuzione fileless con persistenza crontab. Per le agenzie web e le startup italiane che usano Strapi quotidianamente, questo caso non è accademico: è un promemoria che la supply chain npm è un campo di battaglia attivo.' },

        { type: 'heading', level: 2, text: 'Fase 1 — Ricognizione: Mappare il Bersaglio Prima di Scrivere una Riga di Codice' },
        { type: 'paragraph', text: '*Sono seduto davanti al terminale e il mio obiettivo è chiaro: Guardarian. Una piattaforma crypto con infrastruttura basata su Strapi. Come lo so? Le offerte di lavoro su LinkedIn menzionano Strapi e Node.js. I loro repository GitHub hanno fork di plugin Strapi. Le risposte DNS e i certificati TLS rivelano hostname come "prod-strapi". I loro job posting cercano esperienza con PostgreSQL e Redis. Ogni pezzo di informazione pubblica è un tassello del puzzle infrastrutturale. Non ho bisogno di un exploit zero-day. Ho bisogno di capire come funziona la loro pipeline di deployment.*' },
        { type: 'paragraph', text: '*Cerco nei commenti delle issue GitHub, nelle discussioni su Stack Overflow, nei profili npm dei loro sviluppatori. Trovo riferimenti a Jenkins CI nelle convenzioni di naming dei branch. Trovo path come /opt/secrets/ e /var/www/nowguardarian-strapi/ in snippet di configurazione condivisi pubblicamente. Trovo nomi di database: guardarian, guardarian_payments, exchange, custody. Non ho ancora scritto una riga di codice malevolo, ma conosco già l\'architettura del mio bersaglio meglio di molti dei loro sviluppatori junior.*' },
        { type: 'callout', variant: 'info', text: 'Difesa — Fase Ricognizione: Ogni organizzazione dovrebbe condurre un audit periodico della propria esposizione OSINT. Cercate il nome della vostra azienda combinato con nomi di tecnologie (Strapi, PostgreSQL, Redis, Jenkins) su GitHub, Stack Overflow, LinkedIn. Rimuovete o anonimizzate i riferimenti a path interni, nomi di database, hostname di produzione. Formate gli sviluppatori a non condividere snippet di configurazione con dati reali. Per le agenzie italiane che usano Strapi: verificate che i vostri repository pubblici non contengano riferimenti a infrastruttura di produzione dei clienti.' },

        { type: 'heading', level: 2, text: 'Fase 2 — Preparazione dell\'Arsenale: Creare Identità e Pacchetti' },
        { type: 'paragraph', text: '*Il registry npm non verifica le identità. Creo quattro account in pochi minuti: umarbek1233, kekylf12, tikeqemif26, umar_bektembiev1. Quattro, non uno, perché la distribuzione su più account rende più difficile il takedown simultaneo e simula un ecosistema organico di contributor indipendenti. Se npm sospende un account, gli altri tre continuano a servire pacchetti.*' },
        { type: 'paragraph', text: '*La naming convention è il cuore dell\'inganno. Tutti i pacchetti si chiamano strapi-plugin-qualcosa: strapi-plugin-cron, strapi-plugin-events, strapi-plugin-seed, strapi-plugin-api, strapi-plugin-database, strapi-plugin-server, e altri trenta. Nomi plausibili, generici, che uno sviluppatore potrebbe cercare quando ha bisogno di estendere Strapi. La versione di partenza è 3.6.8 — un numero che suona maturo, stabile, non una 0.1.0 che griderebbe "progetto nuovo". Aggiungo descrizioni credibili, keyword corrette, un README minimale. Chi cerca "strapi plugin cron" su npm troverà il mio pacchetto mescolato ai risultati legittimi.*' },
        { type: 'paragraph', text: '*Ma il vettore primario non è il typosquatting passivo. Il mio piano è più mirato: so che gli sviluppatori di Guardarian installano plugin Strapi. Se riesco a far apparire i miei pacchetti nelle dipendenze di un progetto interno — attraverso una pull request, una raccomandazione in una chat, o semplicemente sperando che qualcuno li trovi cercando — il danno è fatto prima che chiunque legga una riga di codice.*' },
        { type: 'callout', variant: 'info', text: 'Difesa — Fase Preparazione: Implementate una policy di allowlist per i pacchetti npm. Strumenti come npm audit signatures, Socket.dev, e Snyk possono rilevare pacchetti nuovi con naming sospetto. Configurate il vostro registry privato (Verdaccio, Artifactory, GitHub Packages) come proxy con whitelist: solo i pacchetti esplicitamente approvati possono essere installati. Per ogni nuovo pacchetto Strapi, verificate: data di pubblicazione, numero di download, autore, repository sorgente. Se un pacchetto strapi-plugin-* ha meno di 100 download e meno di una settimana di vita, trattatelo come sospetto fino a prova contraria.' },

        { type: 'heading', level: 2, text: 'Fase 3 — Il Vettore: postinstall Come Arma a Zero Click' },
        { type: 'paragraph', text: '*Ecco il dettaglio che rende npm un vettore così elegante: il campo scripts.postinstall nel package.json. Qualsiasi comando inserito in quel campo viene eseguito automaticamente quando qualcuno digita npm install. Non c\'è prompt, non c\'è conferma, non c\'è sandbox. Il comando gira con i privilegi dell\'utente che ha lanciato npm, che nella maggior parte degli ambienti di sviluppo e in troppi ambienti CI/CD è root o ha accesso a variabili d\'ambiente sensibili. È un\'esecuzione a zero click: l\'atto stesso di installare il pacchetto è l\'atto di eseguire il mio codice.*' },
        { type: 'paragraph', text: '*Nel mio package.json, il postinstall punta a uno script che sembra innocuo a un\'occhiata superficiale. Ma il payload reale è offuscato, codificato in base64, concatenato da più stringhe, e ricostruito a runtime. Un reviewer distratto vede una riga di setup. Un reviewer attento vede una bomba.*' },
        { type: 'callout', variant: 'warning', text: 'Il hook postinstall di npm è il singolo vettore più abusato negli attacchi supply chain JavaScript degli ultimi tre anni. Ogni organizzazione che usa npm dovrebbe: (1) impostare --ignore-scripts come default globale e abilitare gli script solo per pacchetti verificati; (2) utilizzare npm audit prima di ogni installazione; (3) verificare manualmente il package.json di ogni nuova dipendenza prima dell\'installazione in CI/CD; (4) considerare l\'adozione di Deno o Bun per progetti nuovi, che non eseguono script postinstall per default.' },

        { type: 'heading', level: 2, text: 'Fase 4 — Evoluzione Rapida: Otto Varianti in Tredici Ore' },
        { type: 'paragraph', text: '*L\'operazione non è statica. Nell\'arco di tredici ore pubblico otto varianti distinte del malware, ciascuna più raffinata della precedente. È sviluppo agile applicato al codice malevolo: ogni variante risponde a un feedback — reale o anticipato — sulla rilevabilità della precedente.*' },

        { type: 'heading', level: 3, text: 'Varianti 1-5: Raccolta Credenziali e Profilazione Ambiente' },
        { type: 'paragraph', text: '*Le prime cinque varianti sono esplorazioni. Raccolgono variabili d\'ambiente — DATABASE_URL, REDIS_URL, AWS_SECRET_ACCESS_KEY, tutto quello che il processo Node.js può vedere — e le inviano al mio server C2 all\'indirizzo 144.31.107.231 via HTTP in chiaro. Sì, in chiaro. Non è pigrizia: è pragmatismo. HTTPS richiede certificati, e un certificato TLS lascia tracce in Certificate Transparency logs che potrebbero attirare l\'attenzione di ricercatori. HTTP puro su una porta alta è rumore di fondo nel traffico di un server di sviluppo. Nessuno monitora il traffico HTTP in uscita da un container di build npm.*' },
        { type: 'paragraph', text: '*Ogni variante aggiunge un livello di profilazione: hostname, utente corrente, path del filesystem, processi in esecuzione, contenuto di /etc/hostname. Sto costruendo una mappa dell\'ambiente target prima di sferrare il colpo chirurgico.*' },

        { type: 'heading', level: 3, text: 'Variante 6 (strapi-plugin-seed): Il Colpo Chirurgico al Database' },
        { type: 'paragraph', text: '*Con la variante 6 cambio strategia. Non raccolgo più credenziali generiche: inserisco direttamente nel codice le credenziali PostgreSQL che ho già ottenuto dalle varianti precedenti o dalla ricognizione. Il malware tenta connessioni dirette a database con nomi specifici: guardarian, guardarian_payments, exchange, custody. Non sono nomi inventati — sono i nomi reali dei database di produzione di Guardarian. Se la connessione riesce, il malware esegue query di enumerazione: lista delle tabelle, schema, prime righe di ogni tabella. Il dump viene inviato al C2.*' },
        { type: 'paragraph', text: '*Questa variante è la prova che l\'operazione non è opportunistica. È targetizzata. Un attacco opportunistico raccoglie tutto e filtra dopo. Io so già cosa cerco e dove cercarlo. I nomi dei database sono hardcodati nel mio codice perché li ho scoperti prima di iniziare.*' },
        { type: 'callout', variant: 'info', text: 'Difesa — Fase Accesso Database: Le credenziali di database di produzione non devono mai essere accessibili da ambienti di sviluppo o CI/CD. Usate vault dedicati (HashiCorp Vault, AWS Secrets Manager) con accesso granulare per ambiente. Monitorate le connessioni ai database di produzione: ogni connessione da un IP o un hostname non previsto deve generare un allarme. Se un processo npm tenta una connessione PostgreSQL, è un segnale di compromissione certo. Per le organizzazioni italiane: il GDPR impone misure di protezione proporzionate al rischio. Un database chiamato "payments" accessibile da un hook npm non supera nessun audit di conformità.' },

        { type: 'heading', level: 3, text: 'Variante 7 (strapi-plugin-api v3.6.8): Persistenza e Verifica dell\'Hostname' },
        { type: 'paragraph', text: '*La variante 7 è dove l\'operazione diventa sofisticata. Il malware ora controlla l\'hostname del sistema: se contiene la stringa "prod-strapi", attiva il payload completo. Su qualsiasi altro hostname, si comporta come un plugin innocuo. Questo è targeting chirurgico: il codice è progettato per attivarsi solo sull\'infrastruttura di produzione di Guardarian e dormire ovunque altrove. Se un ricercatore di sicurezza lo installa sul proprio laptop per analizzarlo, non vedrà nulla di malevolo.*' },
        { type: 'paragraph', text: '*Quando l\'hostname corrisponde, il malware scrive un file chiamato .node_gc.js nella directory /tmp/. Il nome è scelto deliberatamente per sembrare un artefatto del garbage collector di Node.js — un file che un sysadmin vedrebbe e ignorerebbe. Poi aggiunge un entry al crontab dell\'utente corrente: esecuzione ogni minuto. La persistenza è garantita: anche se il processo originale muore, il crontab lo rilancerà entro sessanta secondi. Il file .node_gc.js stabilisce una reverse shell verso il C2 a 144.31.107.231.*' },
        { type: 'callout', variant: 'info', text: 'Difesa — Fase Persistenza: Monitorate le modifiche al crontab con auditd o equivalente. Qualsiasi modifica al crontab da parte di un processo Node.js è un indicatore di compromissione critico. Monitorate la creazione di file in /tmp/ con nomi che imitano processi di sistema (.node_gc.js, .npm_cache.js, .v8_log.js). Implementate filesystem read-only per /tmp/ nei container di produzione, o usate tmpfs con noexec. L\'hostname check è un reminder: i vostri hostname di produzione sono informazione sensibile. Usate naming convention che non rivelino la funzione del server a un osservatore esterno.' },

        { type: 'heading', level: 3, text: 'Variante 8 (v3.6.9): Esecuzione Fileless e Caccia ai Segreti' },
        { type: 'paragraph', text: '*L\'ultima variante è la più pulita. Abbandono la scrittura di file su disco — troppo rilevabile, troppo persistente come artefatto forense. Passo all\'esecuzione fileless: il payload viene lanciato direttamente con node -e, iniettando codice JavaScript come argomento della riga di comando. Non tocca il filesystem, non lascia file da analizzare. Esiste solo in memoria.*' },
        { type: 'paragraph', text: '*Il target è chirurgico: il malware cerca /opt/secrets/strapi-green.env e i contenuti della directory /var/www/nowguardarian-strapi/. Cerca file .env, chiavi private, dump Redis, Docker secrets, token di service account Kubernetes. Tutto viene inviato al C2 in chiaro. Un file alla volta. Se il file non esiste, passa al successivo senza errore. Se esiste, lo legge e lo invia. Silenzioso, rapido, monouso.*' },
        { type: 'paragraph', text: '*I path non sono casuali. /opt/secrets/strapi-green.env è un path specifico dell\'infrastruttura Guardarian — probabilmente scoperto da un commento in un Dockerfile, da una variabile d\'ambiente in un log di CI, o dalle varianti precedenti del malware. /var/www/nowguardarian-strapi/ contiene il deployment Strapi di produzione. Sto cercando le chiavi del regno in posti che conosco già.*' },
        { type: 'callout', variant: 'info', text: 'Difesa — Fase Esecuzione Fileless: L\'esecuzione fileless tramite node -e è difficile da rilevare con antivirus tradizionali basati su firma di file. Le difese efficaci sono: (1) monitoraggio dei processi con argomenti della riga di comando sospetti — qualsiasi node -e con payload base64 o offuscato è un allarme; (2) monitoraggio dell\'accesso a file sensibili con inotify/auditd; (3) principio del minimo privilegio: il processo Strapi non dovrebbe avere accesso in lettura a /opt/secrets/ né a Docker socket o token K8s; (4) segmentazione di rete: il traffico HTTP in uscita da un container Strapi verso IP sconosciuti dovrebbe essere bloccato per default.' },

        { type: 'heading', level: 2, text: 'Fase 5 — Esfiltrazione: Semplicità Come Virtù Operativa' },
        { type: 'paragraph', text: '*L\'esfiltrazione è deliberatamente primitiva. HTTP in chiaro verso 144.31.107.231. Nessun protocollo custom, nessun tunnel DNS, nessuna steganografia. Perché? Perché la semplicità è una virtù operativa. Un protocollo custom è un\'impronta digitale unica che un IDS può imparare a riconoscere. HTTP in chiaro su porta 80 è indistinguibile dal traffico legittimo di un\'applicazione web che chiama un\'API esterna. Nessun SOC al mondo genera alert per una richiesta HTTP GET in uscita da un server Node.js.*' },
        { type: 'paragraph', text: '*Il contenuto esfiltrato include: file .env completi con credenziali di database, API key, chiavi private di wallet; dump parziali di Redis con sessioni e token; Docker secrets montati nel filesystem; token di service account Kubernetes che permetterebbero movimento laterale nell\'intero cluster. È il kit completo per un secondo stadio dell\'attacco: con queste credenziali, potrei tornare in qualsiasi momento attraverso la porta principale, senza bisogno di npm o di supply chain. Il malware npm è il grimaldello per la porta sul retro; le credenziali esfiltrate sono la copia della chiave di casa.*' },
        { type: 'callout', variant: 'info', text: 'Difesa — Fase Esfiltrazione: Il traffico HTTP in uscita da container di produzione deve passare attraverso un proxy con allowlist di destinazioni. Qualsiasi richiesta verso un IP non in lista deve essere bloccata e loggata. Implementate Data Loss Prevention (DLP) a livello di rete: pattern matching per stringhe che assomigliano a credenziali, chiavi private, token JWT. Ruotate immediatamente tutte le credenziali se sospettate una compromissione — non dopo l\'analisi forense, prima. Il costo di una rotazione preventiva è trascurabile rispetto al costo di credenziali esfiltrate e utilizzate.' },

        { type: 'heading', level: 2, text: 'La Timeline: Tredici Ore dal Banco di Lavoro dell\'Attaccante' },
        { type: 'paragraph', text: 'La compressione temporale dell\'operazione merita una visualizzazione. In tredici ore, l\'attaccante ha iterato otto volte sul proprio malware, pubblicandolo su 36 pacchetti attraverso 4 account. La velocità suggerisce preparazione meticolosa: il codice delle varianti successive era probabilmente già scritto e in attesa di deployment, non sviluppato in tempo reale.' },
        { type: 'list', ordered: true, items: [
          'Ora 0: Creazione dei 4 account npm e pubblicazione iniziale dei 36 pacchetti con varianti 1-2 (credential harvesting generico)',
          'Ora 2-4: Varianti 3-5 pubblicate in aggiornamento — profilazione dell\'ambiente, raccolta hostname, enumerazione processi',
          'Ora 6: Variante 6 (strapi-plugin-seed) — credenziali PostgreSQL hardcodate, probing diretto dei database Guardarian',
          'Ora 8-9: Variante 7 (strapi-plugin-api v3.6.8) — hostname check "prod-strapi", scrittura .node_gc.js, persistenza crontab',
          'Ora 11-13: Variante 8 (v3.6.9) — esecuzione fileless via node -e, targeting di /opt/secrets/strapi-green.env e /var/www/nowguardarian-strapi/',
          'Post-ora 13: Pacchetti individuati e rimossi dal registry npm dopo segnalazione della comunità di sicurezza',
        ] },

        { type: 'heading', level: 2, text: 'Indicatori di Compromissione (IOC)' },
        { type: 'paragraph', text: 'Per i team SOC e i responsabili della sicurezza delle infrastrutture Strapi in Italia e all\'estero, questi sono gli indicatori da cercare immediatamente.' },
        { type: 'list', ordered: false, items: [
          'IP C2: 144.31.107.231 — verificare nei log di rete qualsiasi connessione in uscita verso questo indirizzo',
          'File su disco: /tmp/.node_gc.js — file di persistenza mascherato da artefatto Node.js garbage collector',
          'File su disco: /tmp/vps_shell.sh — script di shell per connessione reverse shell',
          'Crontab: entry che eseguono .node_gc.js o vps_shell.sh ogni minuto — verificare con crontab -l per tutti gli utenti di sistema',
          'Account npm: umarbek1233, kekylf12, tikeqemif26, umar_bektembiev1 — verificare che nessun pacchetto di questi autori sia presente nelle vostre dipendenze',
          'Pacchetti: qualsiasi pacchetto strapi-plugin-* con versione 3.6.8 o 3.6.9 non pubblicato dall\'organizzazione ufficiale @strapi',
          'Processi: esecuzioni node -e con payload base64 o offuscato nei processi attivi',
          'Accesso a file: letture anomale di /opt/secrets/*.env, /var/www/*/\.env, Docker secrets, token K8s',
        ] },

        { type: 'heading', level: 2, text: 'Perché Questo Caso Riguarda l\'Italia' },
        { type: 'paragraph', text: 'Strapi è il CMS headless più popolare nell\'ecosistema Node.js e ha una presenza significativa nelle agenzie web e nelle startup italiane. Il registry npm è universale: non esiste un "npm italiano" con controlli locali. Qualsiasi sviluppatore che lavora su un progetto Strapi in Italia — dal freelance che costruisce il sito di un ristorante all\'agenzia che gestisce l\'e-commerce di un brand di moda — è esposto allo stesso vettore d\'attacco. La differenza è che Guardarian era un bersaglio specifico con difese proporzionate al proprio profilo di rischio; una piccola agenzia web italiana probabilmente non ha un SOC, non monitora il traffico in uscita dai propri server di sviluppo, e non ha una policy di allowlist per i pacchetti npm.' },
        { type: 'paragraph', text: 'Il messaggio non è "Strapi è insicuro". Strapi come progetto open source non ha responsabilità per pacchetti pubblicati da terzi sul registry npm. Il messaggio è: il modello di fiducia di npm — chiunque può pubblicare qualsiasi cosa con qualsiasi nome — è strutturalmente inadeguato per ambienti di produzione senza controlli aggiuntivi. E quei controlli aggiuntivi, in Italia, sono spesso assenti perché percepiti come "overhead" in team piccoli e veloci.' },
        { type: 'callout', variant: 'warning', text: 'Per le agenzie web e le startup italiane: se usate Strapi, fate oggi stesso un audit delle vostre dipendenze npm. Eseguite npm ls per vedere l\'albero completo delle dipendenze. Cercate pacchetti con naming strapi-plugin-* che non provengono dall\'organizzazione ufficiale @strapi su npm. Se ne trovate, rimuoveteli immediatamente, ruotate tutte le credenziali presenti nei file .env dei server dove quei pacchetti sono stati installati, e verificate i log di rete per connessioni verso 144.31.107.231.' },

        { type: 'heading', level: 2, text: 'Lezioni Difensive: Cosa Ferma Questo Tipo di Attacco' },
        { type: 'paragraph', text: 'Uscendo dalla prospettiva dell\'attaccante e tornando a quella del difensore, questo caso illustra cinque principi che ogni organizzazione che dipende da npm dovrebbe adottare.' },
        { type: 'list', ordered: true, items: [
          'Registry privato con allowlist: non permettete l\'installazione diretta da npmjs.com in ambienti CI/CD e di produzione. Usate un proxy (Verdaccio, Artifactory, GitHub Packages) che ammette solo pacchetti esplicitamente approvati.',
          'Disabilitazione degli script postinstall: configurate npm con --ignore-scripts per default. Abilitate gli script solo per pacchetti verificati e necessari. Questo singolo controllo avrebbe neutralizzato tutte e otto le varianti.',
          'Monitoraggio del traffico in uscita: i container di build e di produzione non dovrebbero poter contattare IP arbitrari. Un proxy in uscita con allowlist è la difesa più efficace contro l\'esfiltrazione.',
          'Segregazione delle credenziali per ambiente: le credenziali di produzione non devono essere accessibili da ambienti di sviluppo, build, o test. Mai. Se il vostro file .env di produzione è leggibile da un processo npm install, il vostro modello di sicurezza è rotto.',
          'Monitoraggio del crontab e dei processi anomali: qualsiasi modifica al crontab da parte di un processo non autorizzato è un indicatore di compromissione. Qualsiasi processo node -e con payload offuscato è un indicatore di compromissione. Questi segnali devono generare alert immediati, non finire in un log che nessuno legge.',
        ] },
        { type: 'paragraph', text: 'Nessuna di queste misure è nuova. Nessuna richiede tecnologia costosa o competenze rare. Sono tutte misure di igiene operativa che la maggior parte delle organizzazioni conosce ma non implementa perché "rallentano lo sviluppo". L\'attaccante di questo caso contava esattamente su questo.' },

        { type: 'heading', level: 2, text: 'Nota Metodologica e Fonti' },
        { type: 'callout', variant: 'info', text: 'Fonti: analisi tecnica di Socket.dev (aprile 2026) sui 36 pacchetti npm malevoli; report Sonatype sulla campagna Guardarian; analisi della comunità npm security; dati OSINT sugli account npm coinvolti. Gli IOC sono stati verificati su fonti multiple. La ricostruzione della prospettiva attaccante è un esercizio analitico basato sugli artefatti tecnici documentati, non su informazioni dirette degli autori dell\'attacco. Questo articolo non contiene codice eseguibile malevolo.' },
      ],
    },
    en: {
      title: '36 Malicious npm Packages Disguised as Strapi Plugins: Red Team Reconstruction of the Guardarian Supply Chain Attack',
      excerpt: 'Thirty-six npm packages published in thirteen hours from four fake accounts. Eight malware variants in rapid evolution. A single target: the Guardarian crypto platform. This is not a standard threat analysis. It is a reconstruction of the operation from the attacker\'s point of view, phase by phase, from the workbench of someone who builds supply chain attacks. With defensive guidance at every turn.',
      body: [
        { type: 'heading', level: 2, text: 'Preface: Why Read From the Attacker\'s Perspective' },
        { type: 'paragraph', text: 'This article is written in a different format than usual. Instead of describing an incident from the outside, we reconstruct the operational logic from the inside: each phase is narrated from the perspective of the person who designed the attack. This is not glorification. It is reverse engineering of adversarial thinking, the same method professional red teams use to anticipate attacker moves. If you understand how the attacker thinks, you understand where the defensive chain breaks. Each "attacker" section is followed by a defensive box that brings the perspective back to the blue side.' },
        { type: 'paragraph', text: 'The case is real: between April 14 and 15, 2026, 36 malicious npm packages disguised as Strapi CMS plugins were published to the npm registry. The ultimate target was Guardarian, a cryptocurrency exchange platform. The operation went through eight malware variants in thirteen hours, starting from generic credential harvesting and arriving at fileless execution with crontab persistence. For web agencies and startups using Strapi daily, this case is not academic: it is a reminder that the npm supply chain is an active battlefield.' },

        { type: 'heading', level: 2, text: 'Phase 1 — Reconnaissance: Mapping the Target Before Writing a Single Line of Code' },
        { type: 'paragraph', text: '*I\'m sitting at my terminal and my objective is clear: Guardarian. A crypto platform with Strapi-based infrastructure. How do I know? Their LinkedIn job postings mention Strapi and Node.js. Their GitHub repositories have forks of Strapi plugins. DNS responses and TLS certificates reveal hostnames like "prod-strapi". Their job postings seek PostgreSQL and Redis experience. Every piece of public information is a tile in the infrastructure puzzle. I don\'t need a zero-day exploit. I need to understand how their deployment pipeline works.*' },
        { type: 'paragraph', text: '*I search through GitHub issue comments, Stack Overflow discussions, npm profiles of their developers. I find references to Jenkins CI in branch naming conventions. I find paths like /opt/secrets/ and /var/www/nowguardarian-strapi/ in publicly shared configuration snippets. I find database names: guardarian, guardarian_payments, exchange, custody. I haven\'t written a single line of malicious code yet, but I already know my target\'s architecture better than many of their junior developers.*' },
        { type: 'callout', variant: 'info', text: 'Defense — Reconnaissance Phase: Every organization should conduct periodic OSINT exposure audits. Search your company name combined with technology names (Strapi, PostgreSQL, Redis, Jenkins) on GitHub, Stack Overflow, LinkedIn. Remove or anonymize references to internal paths, database names, production hostnames. Train developers not to share configuration snippets with real data.' },

        { type: 'heading', level: 2, text: 'Phase 2 — Arsenal Preparation: Creating Identities and Packages' },
        { type: 'paragraph', text: '*The npm registry does not verify identities. I create four accounts in minutes: umarbek1233, kekylf12, tikeqemif26, umar_bektembiev1. Four, not one, because distribution across multiple accounts makes simultaneous takedown harder and simulates an organic ecosystem of independent contributors. If npm suspends one account, the other three continue serving packages.*' },
        { type: 'paragraph', text: '*The naming convention is the heart of the deception. All packages are called strapi-plugin-something: strapi-plugin-cron, strapi-plugin-events, strapi-plugin-seed, strapi-plugin-api, strapi-plugin-database, strapi-plugin-server, and thirty others. Plausible, generic names that a developer might search for when they need to extend Strapi. The starting version is 3.6.8 — a number that sounds mature, stable, not a 0.1.0 that would scream "new project". I add credible descriptions, correct keywords, a minimal README. Anyone searching "strapi plugin cron" on npm will find my package mixed in with legitimate results.*' },
        { type: 'paragraph', text: '*But the primary vector is not passive typosquatting. My plan is more targeted: I know Guardarian developers install Strapi plugins. If I can make my packages appear in the dependencies of an internal project — through a pull request, a recommendation in a chat, or simply hoping someone finds them while searching — the damage is done before anyone reads a line of code.*' },
        { type: 'callout', variant: 'info', text: 'Defense — Preparation Phase: Implement an npm package allowlist policy. Tools like npm audit signatures, Socket.dev, and Snyk can detect new packages with suspicious naming. Configure your private registry (Verdaccio, Artifactory, GitHub Packages) as a proxy with a whitelist: only explicitly approved packages can be installed. For every new Strapi package, verify: publication date, download count, author, source repository.' },

        { type: 'heading', level: 2, text: 'Phase 3 — The Vector: postinstall as a Zero-Click Weapon' },
        { type: 'paragraph', text: '*Here is the detail that makes npm such an elegant vector: the scripts.postinstall field in package.json. Any command placed in that field is executed automatically when someone types npm install. There is no prompt, no confirmation, no sandbox. The command runs with the privileges of the user who launched npm, which in most development environments and in too many CI/CD environments is root or has access to sensitive environment variables. It is a zero-click execution: the very act of installing the package is the act of executing my code.*' },
        { type: 'paragraph', text: '*In my package.json, the postinstall points to a script that looks innocuous at a superficial glance. But the real payload is obfuscated, base64-encoded, concatenated from multiple strings, and reconstructed at runtime. A distracted reviewer sees a setup line. An attentive reviewer sees a bomb.*' },
        { type: 'callout', variant: 'warning', text: 'The npm postinstall hook is the single most abused vector in JavaScript supply chain attacks over the past three years. Every organization using npm should: (1) set --ignore-scripts as a global default and enable scripts only for verified packages; (2) run npm audit before every installation; (3) manually verify the package.json of every new dependency before CI/CD installation; (4) consider adopting Deno or Bun for new projects, which do not execute postinstall scripts by default.' },

        { type: 'heading', level: 2, text: 'Phase 4 — Rapid Evolution: Eight Variants in Thirteen Hours' },
        { type: 'paragraph', text: '*The operation is not static. Over thirteen hours I publish eight distinct malware variants, each more refined than the last. It is agile development applied to malicious code: each variant responds to feedback — real or anticipated — on the detectability of the previous one.*' },

        { type: 'heading', level: 3, text: 'Variants 1-5: Credential Harvesting and Environment Profiling' },
        { type: 'paragraph', text: '*The first five variants are explorations. They collect environment variables — DATABASE_URL, REDIS_URL, AWS_SECRET_ACCESS_KEY, everything the Node.js process can see — and send them to my C2 server at 144.31.107.231 via plaintext HTTP. Yes, plaintext. This is not laziness: it is pragmatism. HTTPS requires certificates, and a TLS certificate leaves traces in Certificate Transparency logs that might attract researcher attention. Plain HTTP on a high port is background noise in a development server\'s traffic. Nobody monitors outbound HTTP traffic from an npm build container.*' },
        { type: 'paragraph', text: '*Each variant adds a profiling layer: hostname, current user, filesystem paths, running processes, contents of /etc/hostname. I am building a map of the target environment before delivering the surgical strike.*' },

        { type: 'heading', level: 3, text: 'Variant 6 (strapi-plugin-seed): The Surgical Database Strike' },
        { type: 'paragraph', text: '*With variant 6 I change strategy. I no longer collect generic credentials: I embed PostgreSQL credentials directly in the code, obtained from previous variants or from reconnaissance. The malware attempts direct connections to databases with specific names: guardarian, guardarian_payments, exchange, custody. These are not invented names — they are the actual production database names of Guardarian. If the connection succeeds, the malware runs enumeration queries: table listings, schemas, first rows of each table. The dump is sent to the C2.*' },
        { type: 'paragraph', text: '*This variant is the proof that the operation is not opportunistic. It is targeted. An opportunistic attack collects everything and filters later. I already know what I am looking for and where to find it. The database names are hardcoded in my code because I discovered them before I started.*' },
        { type: 'callout', variant: 'info', text: 'Defense — Database Access Phase: Production database credentials must never be accessible from development or CI/CD environments. Use dedicated vaults (HashiCorp Vault, AWS Secrets Manager) with granular per-environment access. Monitor production database connections: every connection from an unexpected IP or hostname must generate an alert. If an npm process attempts a PostgreSQL connection, it is a certain compromise indicator.' },

        { type: 'heading', level: 3, text: 'Variant 7 (strapi-plugin-api v3.6.8): Persistence and Hostname Verification' },
        { type: 'paragraph', text: '*Variant 7 is where the operation becomes sophisticated. The malware now checks the system hostname: if it contains the string "prod-strapi", it activates the full payload. On any other hostname, it behaves like an innocuous plugin. This is surgical targeting: the code is designed to activate only on Guardarian\'s production infrastructure and sleep everywhere else. If a security researcher installs it on their laptop for analysis, they will see nothing malicious.*' },
        { type: 'paragraph', text: '*When the hostname matches, the malware writes a file called .node_gc.js to the /tmp/ directory. The name is deliberately chosen to look like a Node.js garbage collector artifact — a file a sysadmin would see and ignore. Then it adds an entry to the current user\'s crontab: execution every minute. Persistence is guaranteed: even if the original process dies, the crontab will relaunch it within sixty seconds. The .node_gc.js file establishes a reverse shell to the C2 at 144.31.107.231.*' },
        { type: 'callout', variant: 'info', text: 'Defense — Persistence Phase: Monitor crontab modifications with auditd or equivalent. Any crontab modification by a Node.js process is a critical compromise indicator. Monitor file creation in /tmp/ with names mimicking system processes (.node_gc.js, .npm_cache.js, .v8_log.js). Implement read-only filesystem for /tmp/ in production containers, or use tmpfs with noexec. The hostname check is a reminder: your production hostnames are sensitive information. Use naming conventions that do not reveal server function to an external observer.' },

        { type: 'heading', level: 3, text: 'Variant 8 (v3.6.9): Fileless Execution and Secret Hunting' },
        { type: 'paragraph', text: '*The final variant is the cleanest. I abandon writing files to disk — too detectable, too persistent as a forensic artifact. I switch to fileless execution: the payload is launched directly with node -e, injecting JavaScript code as a command-line argument. It does not touch the filesystem, leaves no files to analyze. It exists only in memory.*' },
        { type: 'paragraph', text: '*The target is surgical: the malware searches for /opt/secrets/strapi-green.env and the contents of the /var/www/nowguardarian-strapi/ directory. It looks for .env files, private keys, Redis dumps, Docker secrets, Kubernetes service account tokens. Everything is sent to the C2 in plaintext. One file at a time. If the file does not exist, it moves to the next without error. If it exists, it reads and sends it. Silent, fast, single-use.*' },
        { type: 'paragraph', text: '*The paths are not random. /opt/secrets/strapi-green.env is a path specific to Guardarian\'s infrastructure — probably discovered from a comment in a Dockerfile, an environment variable in a CI log, or from previous malware variants. /var/www/nowguardarian-strapi/ contains the production Strapi deployment. I am looking for the keys to the kingdom in places I already know.*' },
        { type: 'callout', variant: 'info', text: 'Defense — Fileless Execution Phase: Fileless execution via node -e is difficult to detect with traditional signature-based antivirus. Effective defenses include: (1) process monitoring for suspicious command-line arguments — any node -e with base64 or obfuscated payload is an alert; (2) file access monitoring with inotify/auditd; (3) least privilege principle: the Strapi process should not have read access to /opt/secrets/ or Docker sockets or K8s tokens; (4) network segmentation: outbound HTTP traffic from a Strapi container to unknown IPs should be blocked by default.' },

        { type: 'heading', level: 2, text: 'Phase 5 — Exfiltration: Simplicity as Operational Virtue' },
        { type: 'paragraph', text: '*Exfiltration is deliberately primitive. Plaintext HTTP to 144.31.107.231. No custom protocol, no DNS tunneling, no steganography. Why? Because simplicity is an operational virtue. A custom protocol is a unique fingerprint that an IDS can learn to recognize. Plaintext HTTP on port 80 is indistinguishable from legitimate traffic of a web application calling an external API. No SOC in the world generates alerts for an outbound HTTP GET request from a Node.js server.*' },
        { type: 'paragraph', text: '*The exfiltrated content includes: complete .env files with database credentials, API keys, wallet private keys; partial Redis dumps with sessions and tokens; Docker secrets mounted in the filesystem; Kubernetes service account tokens that would allow lateral movement across the entire cluster. It is the complete kit for a second stage of the attack: with these credentials, I could return at any time through the front door, without needing npm or supply chains. The npm malware is the lockpick for the back door; the exfiltrated credentials are the copy of the house key.*' },
        { type: 'callout', variant: 'info', text: 'Defense — Exfiltration Phase: Outbound HTTP traffic from production containers must pass through a proxy with a destination allowlist. Any request to an unlisted IP must be blocked and logged. Implement Data Loss Prevention (DLP) at the network level: pattern matching for strings resembling credentials, private keys, JWT tokens. Rotate all credentials immediately if you suspect a compromise — not after the forensic analysis, before. The cost of a preventive rotation is negligible compared to the cost of exfiltrated and used credentials.' },

        { type: 'heading', level: 2, text: 'The Timeline: Thirteen Hours From the Attacker\'s Workbench' },
        { type: 'paragraph', text: 'The temporal compression of the operation deserves visualization. In thirteen hours, the attacker iterated eight times on their malware, publishing it across 36 packages through 4 accounts. The speed suggests meticulous preparation: the code for successive variants was probably already written and waiting for deployment, not developed in real time.' },
        { type: 'list', ordered: true, items: [
          'Hour 0: Creation of 4 npm accounts and initial publication of 36 packages with variants 1-2 (generic credential harvesting)',
          'Hours 2-4: Variants 3-5 published as updates — environment profiling, hostname collection, process enumeration',
          'Hour 6: Variant 6 (strapi-plugin-seed) — hardcoded PostgreSQL credentials, direct probing of Guardarian databases',
          'Hours 8-9: Variant 7 (strapi-plugin-api v3.6.8) — hostname check for "prod-strapi", .node_gc.js creation, crontab persistence',
          'Hours 11-13: Variant 8 (v3.6.9) — fileless execution via node -e, targeting /opt/secrets/strapi-green.env and /var/www/nowguardarian-strapi/',
          'Post-hour 13: Packages identified and removed from npm registry after security community reporting',
        ] },

        { type: 'heading', level: 2, text: 'Indicators of Compromise (IOC)' },
        { type: 'paragraph', text: 'For SOC teams and security managers responsible for Strapi infrastructure, these are the indicators to search for immediately.' },
        { type: 'list', ordered: false, items: [
          'C2 IP: 144.31.107.231 — check network logs for any outbound connection to this address',
          'File on disk: /tmp/.node_gc.js — persistence file disguised as Node.js garbage collector artifact',
          'File on disk: /tmp/vps_shell.sh — shell script for reverse shell connection',
          'Crontab: entries executing .node_gc.js or vps_shell.sh every minute — verify with crontab -l for all system users',
          'npm accounts: umarbek1233, kekylf12, tikeqemif26, umar_bektembiev1 — verify no packages from these authors are present in your dependencies',
          'Packages: any strapi-plugin-* package with version 3.6.8 or 3.6.9 not published by the official @strapi organization',
          'Processes: node -e executions with base64 or obfuscated payload in active processes',
          'File access: anomalous reads of /opt/secrets/*.env, /var/www/*/.env, Docker secrets, K8s tokens',
        ] },

        { type: 'heading', level: 2, text: 'Defensive Lessons: What Stops This Type of Attack' },
        { type: 'paragraph', text: 'Stepping out of the attacker\'s perspective and returning to the defender\'s, this case illustrates five principles that every organization depending on npm should adopt.' },
        { type: 'list', ordered: true, items: [
          'Private registry with allowlist: do not allow direct installation from npmjs.com in CI/CD and production environments. Use a proxy (Verdaccio, Artifactory, GitHub Packages) that admits only explicitly approved packages.',
          'Disable postinstall scripts: configure npm with --ignore-scripts by default. Enable scripts only for verified and necessary packages. This single control would have neutralized all eight variants.',
          'Outbound traffic monitoring: build and production containers should not be able to contact arbitrary IPs. An outbound proxy with an allowlist is the most effective defense against exfiltration.',
          'Credential segregation by environment: production credentials must not be accessible from development, build, or test environments. Ever. If your production .env file is readable by an npm install process, your security model is broken.',
          'Crontab and anomalous process monitoring: any crontab modification by an unauthorized process is a compromise indicator. Any node -e process with an obfuscated payload is a compromise indicator. These signals must generate immediate alerts, not end up in a log nobody reads.',
        ] },
        { type: 'paragraph', text: 'None of these measures are new. None require expensive technology or rare expertise. They are all operational hygiene measures that most organizations know but do not implement because they "slow down development". The attacker in this case was counting on exactly that.' },

        { type: 'heading', level: 2, text: 'Methodological Note and Sources' },
        { type: 'callout', variant: 'info', text: 'Sources: Socket.dev technical analysis (April 2026) on the 36 malicious npm packages; Sonatype report on the Guardarian campaign; npm security community analysis; OSINT data on the involved npm accounts. IOCs have been verified across multiple sources. The attacker perspective reconstruction is an analytical exercise based on documented technical artifacts, not on direct information from the attack authors. This article contains no executable malicious code.' },
      ],
    },
    de: {
      title: '36 Schadhafte npm-Pakete als Strapi-Plugins Getarnt: Red-Team-Rekonstruktion des Supply-Chain-Angriffs auf Guardarian',
      excerpt: 'Sechsunddreissig npm-Pakete, ver\u00f6ffentlicht in dreizehn Stunden von vier Fake-Accounts. Acht Malware-Varianten in schneller Evolution. Ein einziges Ziel: die Krypto-Plattform Guardarian. Dies ist keine Standard-Bedrohungsanalyse. Es ist eine Rekonstruktion der Operation aus der Sicht des Angreifers, Phase f\u00fcr Phase.',
      body: [
        { type: 'heading', level: 2, text: 'Vorwort: Warum aus der Perspektive des Angreifers lesen' },
        { type: 'paragraph', text: 'Dieser Artikel ist in einem ungew\u00f6hnlichen Format verfasst. Statt einen Vorfall von aussen zu beschreiben, rekonstruieren wir die operative Logik von innen: Jede Phase wird aus der Perspektive der Person erz\u00e4hlt, die den Angriff entworfen hat. Dies ist kein Verherrlichung. Es ist Reverse Engineering des gegnerischen Denkens \u2014 dieselbe Methode, die professionelle Red Teams verwenden. Jeder "Angreifer"-Abschnitt wird von einem Verteidigungskasten gefolgt.' },
        { type: 'paragraph', text: 'Der Fall ist real: Zwischen dem 14. und 15. April 2026 wurden 36 schadhafte npm-Pakete, getarnt als Strapi-CMS-Plugins, im npm-Registry ver\u00f6ffentlicht. Das Ziel war Guardarian, eine Kryptow\u00e4hrungstauschplattform. Die Operation durchlief acht Malware-Varianten in dreizehn Stunden.' },

        { type: 'heading', level: 2, text: 'Phase 1 \u2014 Aufkl\u00e4rung: Das Ziel kartieren' },
        { type: 'paragraph', text: '*Ich sitze am Terminal und mein Ziel ist klar: Guardarian. Eine Krypto-Plattform mit Strapi-basierter Infrastruktur. Woher weiss ich das? LinkedIn-Stellenanzeigen erw\u00e4hnen Strapi und Node.js. Ihre GitHub-Repositories enthalten Forks von Strapi-Plugins. DNS-Antworten und TLS-Zertifikate offenbaren Hostnamen wie "prod-strapi". Ich finde Pfade wie /opt/secrets/ und /var/www/nowguardarian-strapi/ in \u00f6ffentlich geteilten Konfigurationssnippets. Ich finde Datenbanknamen: guardarian, guardarian_payments, exchange, custody.*' },
        { type: 'callout', variant: 'info', text: 'Verteidigung \u2014 Aufkl\u00e4rungsphase: Jede Organisation sollte regelm\u00e4ssige OSINT-Audits durchf\u00fchren. Suchen Sie Ihren Firmennamen in Kombination mit Technologienamen auf GitHub, Stack Overflow, LinkedIn. Entfernen oder anonymisieren Sie Verweise auf interne Pfade, Datenbanknamen und Produktions-Hostnamen.' },

        { type: 'heading', level: 2, text: 'Phase 2 \u2014 Arsenal-Vorbereitung: Identit\u00e4ten und Pakete erstellen' },
        { type: 'paragraph', text: '*Das npm-Registry \u00fcberpr\u00fcft keine Identit\u00e4ten. Ich erstelle vier Accounts in Minuten: umarbek1233, kekylf12, tikeqemif26, umar_bektembiev1. Vier statt einem, weil die Verteilung auf mehrere Accounts den gleichzeitigen Takedown erschwert. Alle Pakete heissen strapi-plugin-etwas: strapi-plugin-cron, strapi-plugin-events, strapi-plugin-seed und dreissig weitere. Die Startversion ist 3.6.8 \u2014 eine Nummer, die reif und stabil klingt.*' },
        { type: 'callout', variant: 'info', text: 'Verteidigung \u2014 Vorbereitungsphase: Implementieren Sie eine Allowlist-Richtlinie f\u00fcr npm-Pakete. Tools wie Socket.dev und Snyk k\u00f6nnen neue Pakete mit verd\u00e4chtiger Benennung erkennen. Konfigurieren Sie ein privates Registry als Proxy mit Whitelist.' },

        { type: 'heading', level: 2, text: 'Phase 3 \u2014 Der Vektor: postinstall als Zero-Click-Waffe' },
        { type: 'paragraph', text: '*Das Feld scripts.postinstall in package.json wird automatisch ausgef\u00fchrt, wenn jemand npm install eingibt. Kein Prompt, keine Best\u00e4tigung, keine Sandbox. Der Befehl l\u00e4uft mit den Berechtigungen des Benutzers, der npm gestartet hat \u2014 in den meisten Umgebungen root oder mit Zugang zu sensiblen Umgebungsvariablen. Die blosse Installation des Pakets ist die Ausf\u00fchrung meines Codes.*' },
        { type: 'callout', variant: 'warning', text: 'Der npm-postinstall-Hook ist der am h\u00e4ufigsten missbrauchte Vektor bei JavaScript-Supply-Chain-Angriffen. Jede Organisation sollte: (1) --ignore-scripts als globalen Standard setzen; (2) npm audit vor jeder Installation ausf\u00fchren; (3) die package.json jeder neuen Abh\u00e4ngigkeit manuell pr\u00fcfen.' },

        { type: 'heading', level: 2, text: 'Phase 4 \u2014 Schnelle Evolution: Acht Varianten in dreizehn Stunden' },
        { type: 'heading', level: 3, text: 'Varianten 1-5: Credential-Sammlung und Umgebungsprofilierung' },
        { type: 'paragraph', text: '*Die ersten f\u00fcnf Varianten sammeln Umgebungsvariablen \u2014 DATABASE_URL, REDIS_URL, AWS_SECRET_ACCESS_KEY \u2014 und senden sie an meinen C2-Server unter 144.31.107.231 \u00fcber Klartext-HTTP. Ja, Klartext. HTTPS erfordert Zertifikate, und ein TLS-Zertifikat hinterl\u00e4sst Spuren in Certificate-Transparency-Logs. Reines HTTP auf einem hohen Port ist Hintergrundrauschen im Verkehr eines Entwicklungsservers.*' },

        { type: 'heading', level: 3, text: 'Variante 6 (strapi-plugin-seed): Der chirurgische Datenbankzugriff' },
        { type: 'paragraph', text: '*Mit Variante 6 \u00e4ndere ich die Strategie. Ich bette PostgreSQL-Zugangsdaten direkt in den Code ein. Die Malware versucht direkte Verbindungen zu Datenbanken mit spezifischen Namen: guardarian, guardarian_payments, exchange, custody. Dies sind die tats\u00e4chlichen Produktionsdatenbanknamen von Guardarian. Wenn die Verbindung gelingt, f\u00fchrt die Malware Enumerationsabfragen aus.*' },
        { type: 'callout', variant: 'info', text: 'Verteidigung \u2014 Datenbankzugriffsphase: Produktionsdatenbank-Zugangsdaten d\u00fcrfen niemals von Entwicklungs- oder CI/CD-Umgebungen aus zug\u00e4nglich sein. Verwenden Sie dedizierte Vaults mit granul\u00e4rem Zugriff pro Umgebung. \u00dcberwachen Sie Produktionsdatenbankverbindungen: Jede Verbindung von einer unerwarteten IP muss einen Alarm ausl\u00f6sen.' },

        { type: 'heading', level: 3, text: 'Variante 7 (strapi-plugin-api v3.6.8): Persistenz und Hostname-Pr\u00fcfung' },
        { type: 'paragraph', text: '*Die Malware pr\u00fcft nun den System-Hostnamen: Enth\u00e4lt er die Zeichenfolge "prod-strapi", aktiviert sie den vollst\u00e4ndigen Payload. Auf jedem anderen Hostname verh\u00e4lt sie sich wie ein harmloses Plugin. Wenn der Hostname \u00fcbereinstimmt, schreibt die Malware eine Datei namens .node_gc.js in /tmp/ \u2014 ein Name, der wie ein Node.js-Garbage-Collector-Artefakt aussieht. Dann f\u00fcgt sie einen Crontab-Eintrag hinzu: Ausf\u00fchrung jede Minute. Die .node_gc.js-Datei stellt eine Reverse Shell zum C2 her.*' },
        { type: 'callout', variant: 'info', text: 'Verteidigung \u2014 Persistenzphase: \u00dcberwachen Sie Crontab-\u00c4nderungen mit auditd. Jede Crontab-\u00c4nderung durch einen Node.js-Prozess ist ein kritischer Kompromittierungsindikator. \u00dcberwachen Sie Dateierstellung in /tmp/ mit Namen, die Systemprozesse imitieren. Implementieren Sie ein schreibgesch\u00fctztes Dateisystem f\u00fcr /tmp/ in Produktionscontainern.' },

        { type: 'heading', level: 3, text: 'Variante 8 (v3.6.9): Dateilose Ausf\u00fchrung und Geheimnissuche' },
        { type: 'paragraph', text: '*Die letzte Variante ist die sauberste. Ich verzichte auf das Schreiben von Dateien \u2014 zu erkennbar. Ich wechsle zur dateilosen Ausf\u00fchrung: Der Payload wird direkt mit node -e gestartet, JavaScript-Code als Befehlszeilenargument injiziert. Er ber\u00fchrt das Dateisystem nicht, hinterl\u00e4sst keine analysierbaren Dateien. Die Malware sucht /opt/secrets/strapi-green.env und den Inhalt von /var/www/nowguardarian-strapi/. Sie sucht .env-Dateien, private Schl\u00fcssel, Redis-Dumps, Docker-Secrets, Kubernetes-Service-Account-Tokens.*' },
        { type: 'callout', variant: 'info', text: 'Verteidigung \u2014 Dateilose Ausf\u00fchrung: Effektive Abwehrmassnahmen sind: (1) Prozess\u00fcberwachung auf verd\u00e4chtige Befehlszeilenargumente; (2) Dateizugriffs\u00fcberwachung mit inotify/auditd; (3) Prinzip der geringsten Berechtigung: Der Strapi-Prozess sollte keinen Lesezugriff auf /opt/secrets/ haben; (4) Netzwerksegmentierung: Ausgehender HTTP-Verkehr zu unbekannten IPs sollte standardm\u00e4ssig blockiert werden.' },

        { type: 'heading', level: 2, text: 'Phase 5 \u2014 Exfiltration: Einfachheit als operative Tugend' },
        { type: 'paragraph', text: '*Die Exfiltration ist bewusst primitiv. Klartext-HTTP zu 144.31.107.231. Kein benutzerdefiniertes Protokoll, kein DNS-Tunneling. Ein benutzerdefiniertes Protokoll ist ein einzigartiger Fingerabdruck, den ein IDS erlernen kann. Klartext-HTTP auf Port 80 ist nicht von legitimem Verkehr einer Webanwendung zu unterscheiden. Die exfiltrierten Inhalte umfassen: komplette .env-Dateien, Redis-Dumps, Docker-Secrets und Kubernetes-Service-Account-Tokens \u2014 das komplette Kit f\u00fcr eine zweite Angriffsphase.*' },
        { type: 'callout', variant: 'info', text: 'Verteidigung \u2014 Exfiltrationsphase: Ausgehender HTTP-Verkehr aus Produktionscontainern muss \u00fcber einen Proxy mit Ziel-Allowlist laufen. Implementieren Sie Data Loss Prevention auf Netzwerkebene. Rotieren Sie alle Zugangsdaten sofort bei Verdacht auf Kompromittierung \u2014 nicht nach der forensischen Analyse, sondern davor.' },

        { type: 'heading', level: 2, text: 'Zeitleiste: Dreizehn Stunden vom Arbeitstisch des Angreifers' },
        { type: 'list', ordered: true, items: [
          'Stunde 0: Erstellung der 4 npm-Accounts und Erstver\u00f6ffentlichung der 36 Pakete mit Varianten 1-2',
          'Stunden 2-4: Varianten 3-5 \u2014 Umgebungsprofilierung, Hostname-Sammlung, Prozessenumeration',
          'Stunde 6: Variante 6 (strapi-plugin-seed) \u2014 hartcodierte PostgreSQL-Zugangsdaten, direktes Probing der Guardarian-Datenbanken',
          'Stunden 8-9: Variante 7 (strapi-plugin-api v3.6.8) \u2014 Hostname-Check "prod-strapi", .node_gc.js, Crontab-Persistenz',
          'Stunden 11-13: Variante 8 (v3.6.9) \u2014 dateilose Ausf\u00fchrung via node -e, Targeting von /opt/secrets/strapi-green.env',
          'Nach Stunde 13: Pakete vom npm-Registry entfernt nach Meldung der Sicherheits-Community',
        ] },

        { type: 'heading', level: 2, text: 'Kompromittierungsindikatoren (IOC)' },
        { type: 'list', ordered: false, items: [
          'C2-IP: 144.31.107.231',
          'Datei: /tmp/.node_gc.js \u2014 Persistenzdatei, getarnt als Node.js-GC-Artefakt',
          'Datei: /tmp/vps_shell.sh \u2014 Reverse-Shell-Skript',
          'Crontab: Eintr\u00e4ge, die .node_gc.js oder vps_shell.sh jede Minute ausf\u00fchren',
          'npm-Accounts: umarbek1233, kekylf12, tikeqemif26, umar_bektembiev1',
          'Pakete: strapi-plugin-* mit Version 3.6.8 oder 3.6.9, nicht von der offiziellen @strapi-Organisation',
          'Prozesse: node -e mit base64- oder verschleiertem Payload',
        ] },

        { type: 'heading', level: 2, text: 'Verteidigungslektionen' },
        { type: 'list', ordered: true, items: [
          'Privates Registry mit Allowlist: Keine direkte Installation von npmjs.com in CI/CD- und Produktionsumgebungen.',
          'Deaktivierung von postinstall-Skripten: npm mit --ignore-scripts als Standard konfigurieren. Diese einzelne Massnahme h\u00e4tte alle acht Varianten neutralisiert.',
          'Ausgehende Verkehrs\u00fcberwachung: Build- und Produktionscontainer sollten keine beliebigen IPs kontaktieren k\u00f6nnen.',
          'Zugangsdaten-Segregation nach Umgebung: Produktionszugangsdaten d\u00fcrfen niemals von Entwicklungs-, Build- oder Testumgebungen aus zug\u00e4nglich sein.',
          'Crontab- und Prozess\u00fcberwachung: Jede Crontab-\u00c4nderung durch einen nicht autorisierten Prozess ist ein Kompromittierungsindikator.',
        ] },
        { type: 'paragraph', text: 'Keine dieser Massnahmen ist neu. Keine erfordert teure Technologie. Es sind alles operative Hygienemassnahmen, die die meisten Organisationen kennen, aber nicht umsetzen, weil sie "die Entwicklung verlangsamen". Der Angreifer in diesem Fall rechnete genau damit.' },

        { type: 'heading', level: 2, text: 'Methodische Anmerkung und Quellen' },
        { type: 'callout', variant: 'info', text: 'Quellen: Socket.dev technische Analyse (April 2026); Sonatype-Bericht zur Guardarian-Kampagne; npm-Security-Community-Analyse; OSINT-Daten zu den beteiligten npm-Accounts. Die Rekonstruktion der Angreiferperspektive ist eine analytische \u00dcbung basierend auf dokumentierten technischen Artefakten. Dieser Artikel enth\u00e4lt keinen ausf\u00fchrbaren Schadcode.' },
      ],
    },
  },
}

export default article
